name: 'Continuous Testing CI'
description: 'Add New Relic Synthetic tests to your GitHub workflow'
author: 'New Relic'
inputs:
  new_relic_api_key:
    required: true
    description: 'New Relic API Key'
    type: string
  config_file_path:
    required: true
    description: 'Relative path to JSON configuration file'
    type: string
outputs:
  test_results:
    description: 'Object containing test batch details, such as status, batchId, batchUrl and tests.  The tests object contains details on each individual test executed in the batch.'
runs:
  using: 'node16'
  main: 'dist/index.js'
